name: 'precompute-semantic-release-version-action'
description: 'Pre-compute the next release version (if any) using semantic-release'
branding:
  icon: at-sign
  color: blue

inputs:
  github-token:
    description: "The github token"
  working-directory:
    description: "The path in which semantic-release should run"
    default: "."
  node-version-file:
    description: "The file (default package.json) where the engine to be used is defined"
    default: "package.json"

outputs:
  will-release:
    description: 'Set to true if a new release will be published; false otherwise.'
    value: ${{ steps.precompute-semantic-release-version-action.outputs.will-release }}
  next-version:
    description: "The next version if a new release will be triggered. Empty string if no release will be made."
    value: ${{ steps.precompute-semantic-release-version-action.outputs.next-version }}

runs:
  using: "composite"
  steps:
    - name: Setup Nodejs
      uses: actions/setup-node@v4.0.4
      with:
        node-version-file: ${{ inputs.working-directory }}/${{ inputs.node-version-file }}
    - name: Install Dependecies
      working-directory: ${{ inputs.working-directory }}
      run: npm ci
      shell: bash
    
    - name: Next version
      id: precompute-semantic-release-version-action
      working-directory: ${{ inputs.working-directory }}
      run: |
        mv release.config.mjs baseReleaseConfig.mjs
        cp ${GITHUB_ACTION_PATH}/pre-release.config.mjs ./release.config.mjs
        npx semantic-release --extends=./baseReleaseConfig.mjs --dry-run --no-ci
        if [[ -s .next-version ]]; then
          echo "New release will be triggered: $(cat .next-version)"
          echo "will-release=true" >> $GITHUB_OUTPUT
          echo "next-version=$(cat .next-version)" >> $GITHUB_OUTPUT
        else
          echo "No release will be triggered"
          echo "will-release=false" >> $GITHUB_OUTPUT
        fi
        mv baseReleaseConfig.mjs release.config.mjs
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash
